"""Rasterise the placards and fonts in rasterize.html and write them as C.

usage: python3 tools/assets/build_assets.py

Needs Google Chrome and network access (the fonts come from Google Fonts).
Writes firmware/main/assets_gen.c. Re-run whenever rasterize.html changes.
"""
import json
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = pathlib.Path(__file__).resolve().parents[2]
PAGE = ROOT / "tools/assets/rasterize.html"
OUT = ROOT / "firmware/main/assets_gen.c"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
CONDS = ["NOMINAL", "HEAT", "CRYO", "PRECIP", "WIND", "ELEC", "RANGE", "HUMID", "ARID", "RAD", "VIS", "PRES"]
SIZES = [16, 24, 48, 88]
FONTS = ["JR19", "JR37", "SK8", "SK16", "BS17", "BS20", "BS24", "BS60", "BS104"]
STATUS_PX = 22
STATUS_ICONS = ["CELL", "LINK", "CORE", "STORE", "CHIP", "FEED", "TILT"]
ORBIT_PX = 36
PICTOS = ["SAT", "ROCK", "SUN", "MOON", "ORDER", "MAN", "WOMAN", "GIRL1", "GIRL2", "DOG"]


def render():
    profile = tempfile.mkdtemp(prefix="picpak-assets-")
    cmd = [CHROME, "--headless=new", "--disable-gpu", f"--user-data-dir={profile}",
           "--virtual-time-budget=20000", "--dump-dom", PAGE.as_uri()]
    # Headless Chrome sometimes stays alive after dumping the DOM, so read
    # until the document closes and then kill it.
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
    out, deadline = [], time.time() + 90
    try:
        for line in proc.stdout:
            out.append(line)
            if "</html>" in line or time.time() > deadline:
                break
    finally:
        proc.kill()
        shutil.rmtree(profile, ignore_errors=True)
    m = re.search(r'<pre id="out">(.*?)</pre>', "".join(out), re.S)
    if not m or not m.group(1).strip():
        sys.exit("rasterize.html produced no output (fonts or Chrome failed?)")
    text = m.group(1).replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"').replace("&amp;", "&")
    return json.loads(text)


def pack2(digits):
    data = bytearray((len(digits) + 3) // 4)
    for i, d in enumerate(digits):
        data[i >> 2] |= int(d) << (6 - 2 * (i & 3))
    return data


def pack1(bits):
    data = bytearray((len(bits) + 7) // 8)
    for i, b in enumerate(bits):
        if b == "1":
            data[i >> 3] |= 0x80 >> (i & 7)
    return data


def c_bytes(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        lines.append(indent + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    return "\n".join(lines)


def main():
    d = render()
    bad = [f for f, ok in d["fontCheck"] if not ok]
    if bad:
        sys.exit(f"fonts did not load in Chrome: {bad}")

    parts = ["// Generated by tools/assets/build_assets.py from tools/assets/rasterize.html. Do not edit.",
             '#include "assets.h"', ""]

    # Tiles: one 2 bpp blob per condition, size and severity.
    blob, offsets = bytearray(), []
    for cond in CONDS:
        for s in SIZES:
            for sev in range(3):
                digits = d["tiles"][cond][str(s)][sev]
                assert len(digits) == s * s, (cond, s, sev)
                offsets.append(len(blob))
                blob += pack2(digits)
    parts.append(f"static const uint8_t TILE_DATA[{len(blob)}] = {{\n{c_bytes(blob)}\n}};")
    parts.append(f"static const uint32_t TILE_OFF[{len(offsets)}] = {{ {', '.join(map(str, offsets))} }};")
    parts.append(f"const uint8_t TILE_PX[TILE_SIZES] = {{ {', '.join(map(str, SIZES))} }};")
    parts.append("""
const uint8_t *asset_tile(cond_t c, tile_size_t s, uint8_t sev) {
    if ((unsigned)c >= COND_COUNT || (unsigned)s >= TILE_SIZES || sev > 2) return 0;
    return &TILE_DATA[TILE_OFF[(c * TILE_SIZES + s) * 3 + sev]];
}
""")

    orbits = bytearray()
    assert len(d["orbits"]) == 24
    for digits in d["orbits"]:
        assert len(digits) == ORBIT_PX * ORBIT_PX
        orbits += pack2(digits)
    step = len(orbits) // 24
    parts.append(f"static const uint8_t ORBIT_DATA[{len(orbits)}] = {{\n{c_bytes(orbits)}\n}};")
    parts.append(f"""
const uint8_t *asset_orbit(int hour) {{
    if (hour < 0) hour = 0;
    if (hour > 23) hour = 23;
    return &ORBIT_DATA[hour * {step}];
}}
""")

    status, status_off = bytearray(), []
    assert [x["name"] for x in d["status"]] == STATUS_ICONS
    for icon in d["status"]:
        status_off.append(len(status) // (STATUS_PX * STATUS_PX // 4))
        for digits in icon["tiles"]:
            assert len(digits) == STATUS_PX * STATUS_PX
            status += pack2(digits)
    levels = [x["levels"] for x in d["status"]]
    parts.append(f"static const uint8_t STATUS_DATA[{len(status)}] = {{\n{c_bytes(status)}\n}};")
    parts.append(f"static const uint16_t STATUS_FIRST[{len(status_off)}] = {{ {', '.join(map(str, status_off))} }};")
    parts.append(f"static const uint8_t STATUS_LEVELS[{len(levels)}] = {{ {', '.join(map(str, levels))} }};")
    parts.append(f"""
const uint8_t *asset_status(status_icon_t icon, int level, uint8_t sev) {{
    if ((unsigned)icon >= STI_COUNT || sev > 2) return 0;
    int levels = STATUS_LEVELS[icon];
    if (level < 0) level = 0;
    if (level >= levels) level = levels - 1;
    return &STATUS_DATA[(STATUS_FIRST[icon] + level * 3 + sev) * {STATUS_PX * STATUS_PX // 4}];
}}
""")

    picto, picto_first, picto_px, picto_levels = bytearray(), [], [], []
    assert [x["name"] for x in d["picto"]] == PICTOS
    for p in d["picto"]:
        picto_first.append(len(picto))
        picto_px.append(p["size"])
        picto_levels.append(p["levels"])
        for digits in p["tiles"]:
            assert len(digits) == p["size"] * p["size"]
            picto += pack2(digits)
    parts.append(f"static const uint8_t PICTO_DATA[{len(picto)}] = {{\n{c_bytes(picto)}\n}};")
    parts.append(f"static const uint32_t PICTO_FIRST[{len(picto_first)}] = {{ {', '.join(map(str, picto_first))} }};")
    parts.append(f"static const uint8_t PICTO_LEVELS[{len(picto_levels)}] = {{ {', '.join(map(str, picto_levels))} }};")
    parts.append(f"const uint8_t PICTO_PX[PI_COUNT] = {{ {', '.join(map(str, picto_px))} }};")
    parts.append("""
const uint8_t *asset_picto(picto_t p, int level, uint8_t sev) {
    if ((unsigned)p >= PI_COUNT || sev > 3) return 0;
    int levels = PICTO_LEVELS[p];
    if (level < 0) level = 0;
    if (level >= levels) level = levels - 1;
    int bytes = (PICTO_PX[p] * PICTO_PX[p] + 3) / 4;
    return &PICTO_DATA[PICTO_FIRST[p] + (level * 4 + sev) * bytes];
}
""")

    total = len(blob) + len(orbits) + len(status) + len(picto)
    for name in FONTS:
        glyphs = d["fonts"][name]["glyphs"]
        bits, rows, chars = bytearray(), [], ""
        for g in glyphs:
            ch = g["ch"]
            # Octal for the degree sign: a hex escape would swallow a following hex digit.
            chars += "\\260" if ch == "°" else ch.replace("\\", "\\\\").replace('"', '\\"')
            rows.append(f"    {{ {g['w']}, {g['h']}, {g['xo']}, {g['yo']}, {g['adv']}, {len(bits)} }},")
            bits += pack1(g["bits"])
        total += len(bits) + len(glyphs) * 8
        parts.append(f"static const uint8_t {name}_BITS[{max(1, len(bits))}] = {{\n{c_bytes(bits) if bits else '    0,'}\n}};")
        parts.append(f"static const glyph_t {name}_GLYPHS[{len(glyphs)}] = {{\n" + "\n".join(rows) + "\n};")
        parts.append(f'const font_t FONT_{name} = {{ "{chars}", {len(glyphs)}, {name}_GLYPHS, {name}_BITS }};\n')

    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {total} bytes of asset data")


if __name__ == "__main__":
    main()
