// Placard tiles and bitmap fonts, generated by tools/assets/build_assets.py.
#pragma once
#include <stdint.h>
#include "cond.h"

typedef enum { TILE_16, TILE_24, TILE_48, TILE_88, TILE_SIZES } tile_size_t;
extern const uint8_t TILE_PX[TILE_SIZES];

// 2 bpp, rows top to bottom, same packing as fb.h. NULL for a bad argument.
const uint8_t *asset_tile(cond_t c, tile_size_t s, uint8_t sev);

// One glyph: a 1 bpp bitmap (MSB first, rows top to bottom) placed at
// (pen x + xo, baseline + yo), then the pen moves on by adv.
typedef struct { uint8_t w, h; int8_t xo, yo; uint8_t adv; uint16_t off; } glyph_t;

typedef struct {
    const char *chars;   // one byte per glyph; the degree sign is 0xB0
    uint8_t count;
    const glyph_t *glyphs;
    const uint8_t *bits;
} font_t;

extern const font_t FONT_JR19, FONT_SK8, FONT_SK16, FONT_BS17, FONT_BS20, FONT_BS24, FONT_BS60, FONT_BS104;

// System Updates orbit placard for a story `hour` hours old (clamped to 0-23),
// ORBIT_PX square, 2 bpp.
#define ORBIT_PX 36
const uint8_t *asset_orbit(int hour);

// System Status placards, STATUS_PX square, 2 bpp. CELL and LINK take a level
// of 0-4 (segments or bars); the others ignore it.
typedef enum { STI_CELL, STI_LINK, STI_CORE, STI_STORE, STI_CHIP, STI_FEED, STI_TILT, STI_COUNT } status_icon_t;
#define STATUS_PX 22
const uint8_t *asset_status(status_icon_t icon, int level, uint8_t sev);
