# SPDX-FileCopyrightText: 2026 Field Bureau & Werkstatt LLC
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Check firmware/orders.txt and write it out as firmware/main/orders_gen.c.

usage: python3 tools/orders.py

One order per line as NNN|TEXT, days 001 to 366 in order. Text is uppercase
ASCII that the bitmap fonts carry, 60 to 130 characters, and may use the
tokens {DOG}, {SHIP} and {CO}, which the firmware fills in from config.h.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "firmware/orders.txt"
OUT = ROOT / "firmware/main/orders_gen.c"
ALLOWED = re.compile(r"^[A-Z0-9 .,:;'\-/!?]*$")


def main():
    lines = SRC.read_text().splitlines()
    problems, orders = [], []
    if len(lines) != 366:
        problems.append(f"{len(lines)} lines, want 366")
    for i, line in enumerate(lines, 1):
        m = re.fullmatch(r"(\d{3})\|(.+)", line)
        if not m or int(m.group(1)) != i:
            problems.append(f"line {i}: not numbered {i:03d}")
            continue
        text = m.group(2)
        bare = re.sub(r"\{(DOG|SHIP|CO)\}", "", text)
        if not ALLOWED.match(bare) or "{" in bare or "}" in bare:
            problems.append(f"line {i}: characters outside the font")
        if not 60 <= len(text) <= 130:
            problems.append(f"line {i}: {len(text)} characters")
        orders.append(text)
    if len(set(orders)) != len(orders):
        problems.append("duplicate orders")
    if problems:
        sys.exit("\n".join(problems))
    body = "\n".join('    "' + t.replace("\\", "\\\\").replace('"', '\\"') + '",' for t in orders)
    OUT.write_text("// SPDX-FileCopyrightText: 2026 Field Bureau & Werkstatt LLC\n"
                   "// SPDX-License-Identifier: AGPL-3.0-or-later\n"
                   "// Generated by tools/orders.py from firmware/orders.txt. Do not edit.\n"
                   '#include "orders.h"\n\n'
                   f"const char *const ORDERS[ORDER_COUNT] = {{\n{body}\n}};\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(orders)} orders")


if __name__ == "__main__":
    main()
